project 'Xcode - HaloAPI.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Xcode - HaloAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Xcode - HaloAPI
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Charts', '~> 3.4.0'

  target 'Xcode - HaloAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Xcode - HaloAPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end